name: GitHub Actions

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: setup
      run: make install
    - name: run lint
      run: make lint
    - name: run tests
      run: make tests
    - name: Run test & publish code coverage
      uses: paambaati/codeclimate-action@v5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
           coverageCommand: make test-coverage
           coverageLocations: build/logs/clover.xml:clover
           debug: true